services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.39.134:3306/omastay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=omastay
      - SPRING_DATASOURCE_PASSWORD=omastay18
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
    volumes:
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - my-net1
    restart: always
    volumes:
      - ./conf/:/etc/nginx/conf.d
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - SUBDOMAINS=omastay
      - TOKEN=c57e3ddf-cb5d-401a-bbf4-cb3867f9c8bc
      - LOGFILE=/config/duck.log
    volumes:
      - $HOME/duckdns:/config
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot certonly --manual --preferred-challenges dns -d omastay.duckdns.org -d www.omastay.duckdns.org --manual-auth-hook '/config/duck.sh' --deploy-hook 'nginx -s reload'; sleep 12h & wait $${!}; done;"
    depends_on:
      - duckdns
    restart: unless-stopped

networks:
  my-net1:
    driver: bridge
