version: '3.8'

services:
  # nginx-proxy 설정
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  # 도커 소켓 공유
      - ./certs:/etc/nginx/certs:ro              # SSL 인증서 디렉터리
      - ./vhost.d:/etc/nginx/vhost.d            # 사용자 정의 가상 호스트 설정
      - ./html:/usr/share/nginx/html            # HTML 정적 파일
      - ./dhparam:/etc/nginx/dhparam            # Diffie-Hellman 파라미터
    restart: always
    networks:
      - my-net1

  # Let's Encrypt Companion 설정
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    restart: always
    networks:
      - my-net1

  # Backend 애플리케이션
  backend:
    build:
      context: ./  # Dockerfile 위치
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "9090"  # nginx-proxy가 접근할 수 있도록 포트 노출
    environment:
      - VIRTUAL_HOST=omastay.duckdns.org,www.omastay.duckdns.org
      - LETSENCRYPT_HOST=omastay.duckdns.org,www.omastay.duckdns.org
      - EMAIL=${MAIL_USERNAME}  
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
    restart: always
    networks:
      - my-net1

networks:
  my-net1:
    driver: bridge
