services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile                 
    container_name: backend
    networks:
      - my-net1
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.39.134:3306/omastay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=omastay
      - SPRING_DATASOURCE_PASSWORD=omastay18
    volumes:
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - my-net1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d   # 수정된 설정 파일 디렉토리를 마운트
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    networks:
      - my-net1
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

networks:
  my-net1:
    driver: bridge
