version: '3.9'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./dhparam:/etc/nginx/dhparam
      - ./logs/nginx:/var/log/nginx
    restart: always
    networks:
      - my-net1

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./logs/letsencrypt:/var/log/letsencrypt
    restart: always
    networks:
      - my-net1

  backend:
    build:
      context: ./  # Dockerfile 위치
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "9090"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=omastay.duckdns.org,www.omastay.duckdns.org
      - LETSENCRYPT_HOST=omastay.duckdns.org,www.omastay.duckdns.org
      - LETSENCRYPT_EMAIL=omastay2@gmail.com
      - SPRING_DATASOURCE_URL=jdbc:mysql://3.35.171.211:3306/omastay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=omastay
      - SPRING_DATASOURCE_PASSWORD=omastay18
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
    restart: always
    networks:
      - my-net1

networks:
  my-net1:
    driver: bridge
