version: '3.8'

services:
  # nginx-proxy 설정
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6  # 안정적인 버전 지정
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  # 도커 소켓 공유
      - ./certs:/etc/nginx/certs:ro              # SSL 인증서 디렉터리
    restart: always
    networks:
      - my-net1

  # Let's Encrypt Companion 설정
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
    restart: always
    networks:
      - my-net1

  # Backend 애플리케이션
  backend:
    build:
      context: ./  # Dockerfile 위치
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "9090"  # nginx-proxy가 접근할 수 있도록 포트 노출
    env_file:
      - .env  # .env 파일을 로드하여 환경 변수 설정
    environment:
      - VIRTUAL_HOST=omastay.duckdns.org,www.omastay.duckdns.org  # 두 도메인 추가
      - LETSENCRYPT_HOST=omastay.duckdns.org,www.omastay.duckdns.org  # SSL 인증 도메인 추가
      - LETSENCRYPT_EMAIL=omastay2@gmail.com  # 인증서 알림 받을 이메일
      - SPRING_DATASOURCE_URL=jdbc:mysql://3.35.171.211:3306/omastay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=omastay
      - SPRING_DATASOURCE_PASSWORD=omastay18
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
    restart: always
    networks:
      - my-net1

networks:
  my-net1:
    driver: bridge
