services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://172.31.39.134:3306/omastay?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    restart: always

  nginx:
    image: nginx:latest
    networks:
      - my-net1
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/accounts/live/omastay.duckdns.org:/etc/letsencrypt/live/omastay.duckdns.org
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

networks:
  my-net1:
    driver: bridge
