services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.39.134:3306/omastay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=omastay
      - SPRING_DATASOURCE_PASSWORD=omastay18
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC  # JVM 힙 크기 및 GC 설정
    volumes:
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    restart: always
  nginx:
    image: nginx:latest
    networks:
      - my-net1
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

networks:
  my-net1:
    driver: bridge
