services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.39.134:3306/omastay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=omastay
      - SPRING_DATASOURCE_PASSWORD=omastay18
    volumes:
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: ./nginx  # 여기서 경로가 수정되었습니다.
    networks:
      - my-net1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf  # 기존 경로와 동일합니다.
      - ./nginx/certbot/conf:/etc/letsencrypt  # Certbot 설정 추가.
      - ./nginx/certbot/www:/var/www/certbot  # Certbot 설정 추가.
      - ./nginx/ssl:/etc/nginx/ssl  # SSL 디렉토리 경로 추가.
    depends_on:
      - backend
    command: [ '/bin/sh', '-c', 'nginx -g "daemon off;" & while :; do sleep 6h & wait $${!}; nginx -s reload; done' ]  # Nginx를 주기적으로 재로드하는 명령어 추가.

  certbot:
    image: certbot/certbot
    networks:
      - my-net1
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

networks:
  my-net1:
    driver: bridge
