version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.39.134:3306/omastay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=omastay
      - SPRING_DATASOURCE_PASSWORD=omastay18
      # - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      # - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - my-net1
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts  # SSL 인증서 디렉토리를 마운트
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  my-net1:
    driver: bridge
