server:
  port: 9090
  servlet:
    session:
      timeout: 24h
  tomcat:
    threads:
      max: 80
      min-spare: 5
    max-swallow-size: 20971520  # 20MB
spring:
  datasource:
    url: jdbc:mysql://3.35.171.211:3306/omastay
    username: omastay
    password: omastay18
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 60
      minimum-idle: 10
      idle-timeout: 600000      # 10분
      max-lifetime: 1800000     # 30분
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 1795000 # (29분 55초)
      pool-name: HikariPool
      register-mbeans: true
  main:
    lazy-initialization: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true  # SQL 쿼리를 포맷해서 보기 쉽게 출력
    show-sql: true  # SQL 쿼리를 콘솔에 출력
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: omastay2@gmail.com
    password: pkpauztcsjapcqyr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          encoding: UTF-8
    auth-code-expiration-millis: 180000
  data:
    # Redis aws에 설치함 컴포즈에 만들어야됨
    redis:
      host: 3.35.171.211
      port: 6379
      duration: 600
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:artful-mystery-436200-n4-154c84a846c8.json
        project-id: artful-mystery-436200-n4
        bucket: omastay
  thymeleaf:
    prefix: classpath:/templates/
    cache: true
    enums:
      use-class-for-enum-values: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

custom:
  jwt:
    secretKey: a9sdjfkLSDk093asdf94fuls9juflokasjdf0odsjflkajdfsdsogldfmso9f


#google analytics 전용 [이하운]
oauth:
  client:
    id: your-client-id
    secret: your-client-secret
    refresh-token: your-refresh-token
  google:
    analytics:
      property-id: your-ga4-property-id
      
      
      
      

#건들지 마시오
upload: https://storage.googleapis.com/omastay/
