server:
  port: 9090
  servlet:
    session:
      timeout: 24h
spring:
  datasource:
    url: jdbc:mysql://18.116.238.9:3306/omastay
    username: omastay
    password: omastay18
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 30000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 30000
      pool-name: HikariPool
      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: omastay2@gmail.com
    password: pkpauztcsjapcqyr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          encoding: UTF-8
    auth-code-expiration-millis: 180000
  data:
    # Redis aws에 설치함 컴포즈에 만들어야됨
    redis:
      host: 18.116.238.9
      port: 6379
      duration: 600
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:artful-mystery-436200-n4-154c84a846c8.json
        project-id: artful-mystery-436200-n4
        bucket: omastay
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    enums:
      use-class-for-enum-values: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
decorator:
  datasource:
    p6spy:
      enable-logging: true
custom:
  jwt:
    secretKey: a9sdjfkLSDk093asdf94fuls9juflokasjdf0odsjflkajdfsdsogldfmso9f
upload: https://storage.googleapis.com/omastay/

