name: Java CI with Gradle

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v4

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # SSH 설정
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      # EC2로 파일 복사
      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.HOST }}:/home/ubuntu/OmaStay
      
      # .env 파일을 GitHub Secrets에서 읽어 EC2로 복사
      - name: Create .env file from secrets
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" > .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}" >> .env

      # .env 파일을 EC2에서 생성하는 단계
      - name: Create .env file on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
            echo "DB_URL=${{ secrets.DB_URL }}" > /home/ubuntu/OmaStay/.env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> /home/ubuntu/OmaStay/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /home/ubuntu/OmaStay/.env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> /home/ubuntu/OmaStay/.env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> /home/ubuntu/OmaStay/.env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> /home/ubuntu/OmaStay/.env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> /home/ubuntu/OmaStay/.env
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> /home/ubuntu/OmaStay/.env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> /home/ubuntu/OmaStay/.env
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> /home/ubuntu/OmaStay/.env
            echo "GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}" >> /home/ubuntu/OmaStay/.env
          EOF

      # .env 파일 내용 확인 단계 추가
      - name: Verify .env content on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} "cat /home/ubuntu/OmaStay/.env"

      # .env 파일을 EC2로 복사
      - name: Copy .env to EC2
        run: scp -o StrictHostKeyChecking=no .env ubuntu@${{ secrets.HOST }}:/home/ubuntu/OmaStay/.env

      # Gradle 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      # Gradle 캐시 설정
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod u+x gradlew

      # Gradle 빌드 실행
      - name: Build with Gradle Wrapper
        run: ./gradlew clean build --no-daemon

      # Docker 그룹에 사용자 추가 및 Docker 재시작
      - name: Add ubuntu user to Docker group and restart Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
            sudo usermod -aG docker ubuntu
            sudo systemctl restart docker
            exit
          EOF

      # 8. Docker Compose 실행
      - name: SSH into EC2 and run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
            cd /home/ubuntu/OmaStay
            docker-compose down
            docker-compose up -d --build
          EOF
